const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "923423014149"
const SESSION_ID = "PRABATH-MD~on8mjTyI#E3IeB5lYtW2Hyz_SQTC6JJtKnuZbCe0sKTEOjNpD4yg"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
